// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Caesar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciphertext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Plaintext")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caesar");
                });

            modelBuilder.Entity("Domain.Diffie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BaseG")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ModulusP")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PrivateKeyA")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PrivateKeyB")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PublicKey")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("SharedKey")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Diffie");
                });

            modelBuilder.Entity("Domain.RSA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciphertext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("D")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("E")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("M")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("N")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("P")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Plaintext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Q")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("RSAs");
                });
#pragma warning restore 612, 618
        }
    }
}
